# Sample Code for Trees (mainly generated by ChatGPT):
# Load the necessary packages
library(caret) # for general model fitting
library(rpart) # for fitting decision trees
library(ipred) # for fitting bagged decision trees
library(randomForest) # for fitting random forests
library(gbm) # for fitting boosted trees

# Load the built-in dataset mtcars
data(mtcars)

# Split the data into training and testing sets (70% and 30%)
set.seed(123) # for reproducibility
train_index <- createDataPartition(mtcars$mpg, p = 0.7, list = FALSE)
# or :
## N <- nrow(mtcars); n <- ceiling(N*0.7); train_index <- sample.int(N, n)
train_data <- mtcars[train_index, ]
test_data <- mtcars[-train_index, ]

# Fit a single decision tree
tree_model <- rpart(mpg ~ ., data = train_data)
tree_pred <- predict(tree_model, newdata = test_data)
tree_mse <- mean((tree_pred - test_data$mpg)^2) # mean squared error
cat("MSE of single decision tree:", tree_mse, "\n")

# Fit a bagged model with 100 bootstrap samples
bag_model <- bagging(mpg ~ ., data = train_data, nbagg = 100)
bag_pred <- predict(bag_model, newdata = test_data)
bag_mse <- mean((bag_pred - test_data$mpg)^2) # mean squared error
cat("MSE of bagged model:", bag_mse, "\n")

# Fit a random forest model with 100 trees and 3 variables randomly sampled at each split
rf_model <- randomForest(mpg ~ ., data = train_data, ntree = 100, mtry = 3)
rf_pred <- predict(rf_model, newdata = test_data)
rf_mse <- mean((rf_pred - test_data$mpg)^2) # mean squared error
cat("MSE of random forest model:", rf_mse, "\n")

# Fit a boosted model with 100 trees and a shrinkage parameter of 0.1
boost_model <- gbm(mpg ~ ., data = train_data,
                   distribution = "gaussian", n.trees = 100, shrinkage = 0.1,
                   # To avoid error: `nTrain * bag.fraction <= n.minobsinnode`
                   bag.fraction = .5, train.fraction = 1, n.minobsinnode=7)
boost_pred <- predict(boost_model, newdata = test_data, n.trees = 100)
boost_mse <- mean((boost_pred - test_data$mpg)^2) # mean squared error
cat("MSE of boosted model:", boost_mse, "\n")
